INSERT INTO Actividades (
                       num_actividad,
                       curso, 
                       titulo,
                       descripcion,
                       jornadas,
                       fecha_inicio,
                       fecha_fin,
                       hora_inicio,
                       hora_fin,
                       dia_completo,
                       horas_lectivas,
                       eval,
                       cursos,
                       observaciones_cursos_horas,
                       especialidad,
                       tramo_horario,
                       num_alumnos,
                       lugar_celebracion,
                       colaboracion_coordinador,
                       colaboracion_departamentos,
                       profesores_participantes,
                       que_hacen_afectados,
                       observaciones,
                       adjuntos,
                       categorias,
                       estado,
                       departamento_id,
                       coordinador_id,
                       email,
                       nombre
                    )
                    VALUES (
						null,
                       '23/24', 
                       'Viaje fin de Curso 4ESO',
                       'Recorrido Pirineos, Andorra, Barcelona y Salou',
                       8,
                       '2024/05/12',
                       '2024/05/20',
                       '12:00',
                       '15:00',
                       true,
                       20,
                       '2',
                       '4ESOA, 4ESOB',
                       '4ESOA irá a las 20:30',
                       'Secundaria',
                       '2; 3; 4',
                       20,
                       'Cataluña',
                       'Departamento de Historia y Filosofía',
                       'Colaboraciones varias',
                       'Maínez Venegas, Isidro José; Martín Soriano, Manuel María; Olmedo Bellido, Isabel',
                       1,
                       'Actividad de prueba',
                       null,
                       'Viaje',
                       'Borrador',
                       1,
                       20,
                       'nerom24@gmail.com',
                       'Moreno Jiménez, Juan Carlos'
                    );
alter table actividades modify column estado ENUM ('Borrador', 'Planificado', 'Validado', 'Difundido', 'Archivado', 'Cancelado', 'Celebrado');
alter table actividades add column user_id int unsigned;
alter table actividades add constraint foreign key (user_id) references users(id) 
    ON delete SET NULL ON UPDATE CASCADE